### ISSUE TITLE
顶部按钮文字遮挡

### ISSUE THREAD

**Issue by Tonyjiang666** [ABCalculator/app#2]
安卓机上顶部按钮的文字会被按钮大小遮挡
[IMG_1503.pdf](https://github.com/ABCalculator/app/files/10865008/IMG_1503.pdf)

**Comment by Mehver** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/75297777/222257484-f60996f3-7b7e-4392-91ef-5a5a8d64243e.png">
